<a href="https://colab.research.google.com/github/NasimulNabil/Ai-Lab/blob/main/Ai(Lab)3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#list
list0=[1,2,3,2.23,54,'Anaconda',[2,34,5]]
print(list0)
list1=[]
print(list1)
list2=list()
print(list2)

[1, 2, 3, 2.23, 54, 'Anaconda', [2, 34, 5]]
[]
[]


In [ ]:
#iterative list
list0=[1,2,3,2.23,54,'python3.7',[2,34,5]]
for i in list0:
  print(i,end='')
print('')

1232.2354python3.7[2, 34, 5]


In [ ]:
#tuple
tp0=[1,2,3,2.23,54,'Coffee',[2,34,5]]
print(tp0)
tp1=()
print(tp1)
tp2=tuple()
print(tp1)


[1, 2, 3, 2.23, 54, 'Coffee', [2, 34, 5]]
()
()


In [ ]:
# create object

class Ball():
  def __init__(self):
    print(f'Ball created')
  def who_i_am(self):
    print(f'i have a cricket ball')

In [ ]:
#create a child(footbalclass)
class Football(Ball):
  def __init__(self):
    # create instance
    Ball. __init__(self)
    print(f'football created')

In [ ]:
#create object
myFootball=Football()

Ball created
football created


In [ ]:
#call base method
myFootball.who_i_am()

i have a cricket ball


In [ ]:
#create overridding
class Football(Ball):
  def __init__(self):
    # create instance
    Ball. __init__(self)
    print(f'football created')


In [ ]:
#override
def who_i_am(self):
  print(f'i have a cricket ball')

In [ ]:
#object
myFootball=Football()

Ball created
football created


In [ ]:
myFootball.who_i_am()

i have a cricket ball


In [ ]:
import numpy as np
numbers=np.array([2,3,4,5,6])
numbers

array([2, 3, 4, 5, 6])

In [ ]:
#2D array
number1=np.array([[1,2,3,4],[9,8,7,6]])
number1

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [ ]:
#3D array
number3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
number3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])