<a href="https://colab.research.google.com/github/NasimulNabil/Ai-Lab/blob/main/Ai(Lab_4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
[str(c) for c in L]

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [ ]:
[type(item) for item in L]

[int, int, int, int, int, int, int, int, int, int]

In [ ]:
np.zeros(10,dtype='float')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones((3,5), dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
x1 = np.array([[4,3,5,7,8],
              [5,6,7,8,0]])
x1

array([[4, 3, 5, 7, 8],
       [5, 6, 7, 8, 0]])

In [ ]:
x1[2]

5

In [ ]:
x1[-3]

5

In [ ]:
x1[0,2]

5

In [ ]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
#array slicing
x[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
x[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
x[2:5]

array([2, 3, 4])

In [ ]:
x[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
x [::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [ ]:
a = np.array([1,2,3])
b = np.array([2,7,0])
c = np.array([6,2,5])

In [ ]:
np.concatenate([a,b,c])

array([1, 2, 3, 2, 7, 0, 6, 2, 5])

**Pandas**

In [ ]:
import pandas as pd


In [ ]:
data = {
    'apple':[3,2,0,1],
    'orange':[5,8,9,0]
}

In [ ]:
purchase = pd.DataFrame(data)
purchase

apple  orange
0      3       5
1      2       8
2      0       9
3      1       0

In [ ]:
purchase = pd.DataFrame(data, index=['A','E','I','O'])
purchase

apple  orange
A      3       5
E      2       8
I      0       9
O      1       0

In [ ]:
data = pd.DataFrame({'country':['Bangladesh','India','Japan','China'],
                      'Rank':['111','34','45','66']
                     })
data

country Rank
0  Bangladesh  111
1       India   34
2       Japan   45
3       China   66

In [ ]:
data.describe()


country Rank
count        4    4
unique       4    4
top      China   45
freq         1    1

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   country  4 non-null      object
 1   Rank     4 non-null      object
dtypes: object(2)
memory usage: 192.0+ bytes


In [ ]:
import pandas as pd 
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/iris_csv.csv")

In [ ]:
df

sepallength  sepalwidth  petallength  petalwidth           class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
df.head()

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [ ]:
df.head(10)

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa
5          5.4         3.9          1.7         0.4  Iris-setosa
6          4.6         3.4          1.4         0.3  Iris-setosa
7          5.0         3.4          1.5         0.2  Iris-setosa
8          4.4         2.9          1.4         0.2  Iris-setosa
9          4.9         3.1          1.5         0.1  Iris-setosa

In [ ]:
df.columns

Index(['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'class'], dtype='object')

In [ ]:
df.shape

(150, 5)

In [ ]:
df.tail()

sepallength  sepalwidth  petallength  petalwidth           class
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

In [ ]:
print(df[10:21])

    sepallength  sepalwidth  petallength  petalwidth        class
10          5.4         3.7          1.5         0.2  Iris-setosa
11          4.8         3.4          1.6         0.2  Iris-setosa
12          4.8         3.0          1.4         0.1  Iris-setosa
13          4.3         3.0          1.1         0.1  Iris-setosa
14          5.8         4.0          1.2         0.2  Iris-setosa
15          5.7         4.4          1.5         0.4  Iris-setosa
16          5.4         3.9          1.3         0.4  Iris-setosa
17          5.1         3.5          1.4         0.3  Iris-setosa
18          5.7         3.8          1.7         0.3  Iris-setosa
19          5.1         3.8          1.5         0.3  Iris-setosa
20          5.4         3.4          1.7         0.2  Iris-setosa
